//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oagum0._01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArticleAuthorRelationshipEntities : DbContext
    {
        public ArticleAuthorRelationshipEntities()
            : base("name=ArticleAuthorRelationshipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Article> T_Article { get; set; }
        public virtual DbSet<T_ArticleAuthor> T_ArticleAuthor { get; set; }
        public virtual DbSet<T_Author> T_Author { get; set; }
    }
}
