//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oagum0._01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PublisherSmallMeDa
    {
        public string Title { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public string Publisher { get; set; }
        public string Link { get; set; }
        public int ID { get; set; }
    }
}
