//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oagum0._01.extrafiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Publisher
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> CreatedUser { get; set; }
    }
}
