// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Explore site
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIRegisterHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumAmalgumDocument.UIRegisterHyperlink;
            HtmlCustom uIItemCustom = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIItemCustom;
            HtmlDocument uIAmalgumRegisterDocument = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument;
            WinButton uICloseButton = this.UIAmalgumAmalgumInternWindow.UINotificationToolBar.UICloseButton;
            HtmlEdit uIEmailAddressEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIEmailAddressEdit;
            HtmlEdit uISubmitEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UISubmitEdit;
            HtmlEdit uIUsernameEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIPasswordEdit;
            HtmlEdit uIConfirmpasswordEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIConfirmpasswordEdit;
            HtmlHyperlink uILoginHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UILoginEdit;
            HtmlEdit uISearchStringEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumAmalgumDocument1.UISearchStringEdit;
            HtmlHyperlink uIItem1stNanoIBCTConfeHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument.UIItem1stNanoIBCTConfeHyperlink;
            HtmlDocument uIAmalgumResultsDocument = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument;
            WinButton uICloseButton1 = this.UIAccessibilitySetupAsWindow.UIAccessibilitySetupAsTitleBar.UICloseButton;
            WinButton uICancelButton = this.UIReadingUntaggedDocumWindow.UIItemWindow.UIItemGroup.UICancelButton;
            BrowserWindow uIAmalgumAmalgumInternWindow = this.UIAmalgumAmalgumInternWindow;
            HtmlHyperlink uIFavoritesHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument.UIFavoritesHyperlink;
            HtmlDiv uIAmalgumPane1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UIAmalgumPane.UIAmalgumPane1;
            HtmlHyperlink uILoginHyperlink1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UILoginHyperlink;
            HtmlDiv uIItemPane = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UIAmalgumPane.UIItemPane;
            HtmlHyperlink uILogoutHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UILogoutHyperlink;
            #endregion


            // Click 'Register' link
            Mouse.Click(uIRegisterHyperlink, new Point(38, 28));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Move 'Amalgum - Register' document
            Mouse.StartDragging(uIAmalgumRegisterDocument, new Point(976, 171));
            Mouse.StopDragging(uIAmalgumRegisterDocument, 0, 38);

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(7, 9));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'EmailAddress' text box
            Mouse.Click(uIEmailAddressEdit, new Point(183, 2));

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(120, 9));

            // Move 'Amalgum - Register' document
            Mouse.StartDragging(uIAmalgumRegisterDocument, new Point(975, 219));
            Mouse.StopDragging(uIAmalgumRegisterDocument, -2, 7);

            // Type 'thisemail@this.com' in 'EmailAddress' text box
            uIEmailAddressEdit.Text = this.RecordedMethod1Params.UIEmailAddressEditText;

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(165, 16));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod1Params.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod1Params.UIPasswordEditPassword;

            // Type '********' in 'Confirm password' text box
            uIConfirmpasswordEdit.Password = this.RecordedMethod1Params.UIConfirmpasswordEditPassword;

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(58, 19));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(22, 31));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit1.Text = this.RecordedMethod1Params.UIUsernameEditText1;

            // Type '********' in 'Password' text box
            uIPasswordEdit1.Password = this.RecordedMethod1Params.UIPasswordEditPassword1;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(73, 18));

            // Type 'radiation' in 'searchString' text box
            uISearchStringEdit.Text = this.RecordedMethod1Params.UISearchStringEditText;

            // Type '{Enter}' in 'searchString' text box
            Keyboard.SendKeys(uISearchStringEdit, this.RecordedMethod1Params.UISearchStringEditSendKeys, ModifierKeys.None);

            // Click '1st Nano-IBCT Conference 2011 u2013 Radiation Dam...' link
            Mouse.Click(uIItem1stNanoIBCTConfeHyperlink, new Point(510, 10));

            // Move 'Amalgum - Results' document
            Mouse.StartDragging(uIAmalgumResultsDocument, new Point(976, 390));
            Mouse.StopDragging(uIAmalgumResultsDocument, 0, -9);

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(26, 19));

            // Click '&Cancel' button
            Mouse.Click(uICancelButton, new Point(37, 20));

            // Maximize window 'Amalgum - Amalgum - Internet Explorer'
            uIAmalgumAmalgumInternWindow.Maximized = this.RecordedMethod1Params.UIAmalgumAmalgumInternWindowMaximized;

            // Move 'Amalgum - Results' document
            Mouse.StartDragging(uIAmalgumResultsDocument, new Point(1599, 527));
            Mouse.StopDragging(uIAmalgumResultsDocument, 0, -432);

            // Click 'Favorites' link
            Mouse.Click(uIFavoritesHyperlink, new Point(25, 30));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Amalgum' pane at (1, 1)
            Mouse.Hover(uIAmalgumPane1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Move 'Log in' link to pane
            uIItemPane.EnsureClickable(new Point(1044, 15));
            Mouse.StartDragging(uILoginHyperlink1, new Point(33, 20));
            Mouse.StopDragging(uIItemPane, new Point(1044, 15));

            // Click 'Logout' link
            Mouse.Click(uILogoutHyperlink, new Point(18, 25));
        }
        
        /// <summary>
        /// site explore
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            HtmlHyperlink uIRegisterHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumAmalgumDocument.UIRegisterHyperlink;
            HtmlDocument uIAmalgumRegisterDocument = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument;
            HtmlEdit uISubmitEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UISubmitEdit;
            HtmlEdit uIEmailAddressEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIEmailAddressEdit;
            HtmlEdit uIUsernameEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIPasswordEdit;
            HtmlEdit uIConfirmpasswordEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UIConfirmpasswordEdit;
            HtmlHyperlink uILoginHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumRegisterDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumLoginDocument.UILoginEdit;
            HtmlEdit uISearchStringEdit = this.UIAmalgumAmalgumInternWindow.UIAmalgumAmalgumDocument1.UISearchStringEdit;
            HtmlHyperlink uIFavoritesHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument.UIFavoritesHyperlink;
            HtmlDiv uIResultsarticlesfoundPane = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UIResultsarticlesfoundPane;
            HtmlDocument uIAmalgumResultsDocument1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1;
            HtmlDiv uIAmalgumAnOpenAccePane = this.UIAmalgumAmalgumInternWindow.UIAmalgumAmalgumDocument.UIAmalgumAnOpenAccePane;
            HtmlHyperlink uIFavoritesHyperlink1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UIFavoritesHyperlink;
            HtmlDiv uIItemPane1 = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UIAmalgumPane.UIItemPane1;
            HtmlHyperlink uILogoutHyperlink = this.UIAmalgumAmalgumInternWindow.UIAmalgumResultsDocument1.UILogoutHyperlink;
            #endregion

            // Go to web page 'http://localhost:50380/' using new browser instance
            this.UIAmalgumAmalgumInternWindow.LaunchUrl(new System.Uri(this.RecordedMethod2Params.UIAmalgumAmalgumInternWindowUrl));

            // Click 'Register' link
            Mouse.Click(uIRegisterHyperlink, new Point(61, 39));

            // Move 'Amalgum - Register' document
            Mouse.StartDragging(uIAmalgumRegisterDocument, new Point(979, 134));
            Mouse.StopDragging(uIAmalgumRegisterDocument, -2, 37);

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(116, 22));

            // Type 'thisemail@mail.this' in 'EmailAddress' text box
            uIEmailAddressEdit.Text = this.RecordedMethod2Params.UIEmailAddressEditText;

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(97, 23));

            // Type 'thisemail@mail.this.com' in 'EmailAddress' text box
            uIEmailAddressEdit.Text = this.RecordedMethod2Params.UIEmailAddressEditText1;

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(118, 2));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod2Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod2Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod2Params.UIPasswordEditPassword;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.RecordedMethod2Params.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Confirm password' text box
            uIConfirmpasswordEdit.Password = this.RecordedMethod2Params.UIConfirmpasswordEditPassword;

            // Click 'submit' text box
            Mouse.Click(uISubmitEdit, new Point(102, 17));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(30, 23));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit1.Text = this.RecordedMethod2Params.UIUsernameEditText1;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit1, this.RecordedMethod2Params.UIUsernameEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit1.Password = this.RecordedMethod2Params.UIPasswordEditPassword1;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(86, 7));

            // Type 'radiation' in 'searchString' text box
            uISearchStringEdit.Text = this.RecordedMethod2Params.UISearchStringEditText;

            // Type '{Enter}' in 'searchString' text box
            Keyboard.SendKeys(uISearchStringEdit, this.RecordedMethod2Params.UISearchStringEditSendKeys, ModifierKeys.None);

            // Click 'Favorites' link
            Mouse.Click(uIFavoritesHyperlink, new Point(32, 20));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Results articles found' pane at (1, 1)
            Mouse.Hover(uIResultsarticlesfoundPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Move 'Amalgum - Results' document to 'Amalgum An Open Acce' pane
            uIAmalgumAnOpenAccePane.EnsureClickable(new Point(327, 134));
            Mouse.StartDragging(uIAmalgumResultsDocument1, new Point(976, 124));
            Mouse.StopDragging(uIAmalgumAnOpenAccePane, new Point(327, 134));

            // Click 'Favorites' link
            Mouse.Click(uIFavoritesHyperlink1, new Point(35, 15));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Logout' link
            Mouse.Click(uILogoutHyperlink, new Point(45, 20));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UIAmalgumAmalgumInternWindow UIAmalgumAmalgumInternWindow
        {
            get
            {
                if ((this.mUIAmalgumAmalgumInternWindow == null))
                {
                    this.mUIAmalgumAmalgumInternWindow = new UIAmalgumAmalgumInternWindow();
                }
                return this.mUIAmalgumAmalgumInternWindow;
            }
        }
        
        public UIAccessibilitySetupAsWindow UIAccessibilitySetupAsWindow
        {
            get
            {
                if ((this.mUIAccessibilitySetupAsWindow == null))
                {
                    this.mUIAccessibilitySetupAsWindow = new UIAccessibilitySetupAsWindow();
                }
                return this.mUIAccessibilitySetupAsWindow;
            }
        }
        
        public UIReadingUntaggedDocumWindow UIReadingUntaggedDocumWindow
        {
            get
            {
                if ((this.mUIReadingUntaggedDocumWindow == null))
                {
                    this.mUIReadingUntaggedDocumWindow = new UIReadingUntaggedDocumWindow();
                }
                return this.mUIReadingUntaggedDocumWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UIAmalgumAmalgumInternWindow mUIAmalgumAmalgumInternWindow;
        
        private UIAccessibilitySetupAsWindow mUIAccessibilitySetupAsWindow;
        
        private UIReadingUntaggedDocumWindow mUIReadingUntaggedDocumWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'thisemail@this.com' in 'EmailAddress' text box
        /// </summary>
        public string UIEmailAddressEditText = "thisemail@this.com";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type '********' in 'Confirm password' text box
        /// </summary>
        public string UIConfirmpasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText1 = "shaymas123";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword1 = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type 'radiation' in 'searchString' text box
        /// </summary>
        public string UISearchStringEditText = "radiation";
        
        /// <summary>
        /// Type '{Enter}' in 'searchString' text box
        /// </summary>
        public string UISearchStringEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Maximize window 'Amalgum - Amalgum - Internet Explorer'
        /// </summary>
        public bool UIAmalgumAmalgumInternWindowMaximized = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:50380/' using new browser instance
        /// </summary>
        public string UIAmalgumAmalgumInternWindowUrl = "http://localhost:50380/";
        
        /// <summary>
        /// Type 'thisemail@mail.this' in 'EmailAddress' text box
        /// </summary>
        public string UIEmailAddressEditText = "thisemail@mail.this";
        
        /// <summary>
        /// Type 'thisemail@mail.this.com' in 'EmailAddress' text box
        /// </summary>
        public string UIEmailAddressEditText1 = "thisemail@mail.this.com";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Confirm password' text box
        /// </summary>
        public string UIConfirmpasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText1 = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword1 = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        
        /// <summary>
        /// Type 'radiation' in 'searchString' text box
        /// </summary>
        public string UISearchStringEditText = "radiation";
        
        /// <summary>
        /// Type '{Enter}' in 'searchString' text box
        /// </summary>
        public string UISearchStringEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumAmalgumInternWindow : BrowserWindow
    {
        
        public UIAmalgumAmalgumInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Amalgum - Amalgum";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Amalgum - Amalgum");
            this.WindowTitles.Add("Amalgum - Register");
            this.WindowTitles.Add("Amalgum - Log in");
            this.WindowTitles.Add("Amalgum - Results");
            this.WindowTitles.Add("AOL.com - News, Sports, Weather, Entertainment, Stocks & Local");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAmalgumAmalgumDocument UIAmalgumAmalgumDocument
        {
            get
            {
                if ((this.mUIAmalgumAmalgumDocument == null))
                {
                    this.mUIAmalgumAmalgumDocument = new UIAmalgumAmalgumDocument(this);
                }
                return this.mUIAmalgumAmalgumDocument;
            }
        }
        
        public UIAmalgumRegisterDocument UIAmalgumRegisterDocument
        {
            get
            {
                if ((this.mUIAmalgumRegisterDocument == null))
                {
                    this.mUIAmalgumRegisterDocument = new UIAmalgumRegisterDocument(this);
                }
                return this.mUIAmalgumRegisterDocument;
            }
        }
        
        public UINotificationToolBar UINotificationToolBar
        {
            get
            {
                if ((this.mUINotificationToolBar == null))
                {
                    this.mUINotificationToolBar = new UINotificationToolBar(this);
                }
                return this.mUINotificationToolBar;
            }
        }
        
        public UIAmalgumLoginDocument UIAmalgumLoginDocument
        {
            get
            {
                if ((this.mUIAmalgumLoginDocument == null))
                {
                    this.mUIAmalgumLoginDocument = new UIAmalgumLoginDocument(this);
                }
                return this.mUIAmalgumLoginDocument;
            }
        }
        
        public UIAmalgumAmalgumDocument1 UIAmalgumAmalgumDocument1
        {
            get
            {
                if ((this.mUIAmalgumAmalgumDocument1 == null))
                {
                    this.mUIAmalgumAmalgumDocument1 = new UIAmalgumAmalgumDocument1(this);
                }
                return this.mUIAmalgumAmalgumDocument1;
            }
        }
        
        public UIAmalgumResultsDocument UIAmalgumResultsDocument
        {
            get
            {
                if ((this.mUIAmalgumResultsDocument == null))
                {
                    this.mUIAmalgumResultsDocument = new UIAmalgumResultsDocument(this);
                }
                return this.mUIAmalgumResultsDocument;
            }
        }
        
        public UIAmalgumResultsDocument1 UIAmalgumResultsDocument1
        {
            get
            {
                if ((this.mUIAmalgumResultsDocument1 == null))
                {
                    this.mUIAmalgumResultsDocument1 = new UIAmalgumResultsDocument1(this);
                }
                return this.mUIAmalgumResultsDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIAmalgumAmalgumDocument mUIAmalgumAmalgumDocument;
        
        private UIAmalgumRegisterDocument mUIAmalgumRegisterDocument;
        
        private UINotificationToolBar mUINotificationToolBar;
        
        private UIAmalgumLoginDocument mUIAmalgumLoginDocument;
        
        private UIAmalgumAmalgumDocument1 mUIAmalgumAmalgumDocument1;
        
        private UIAmalgumResultsDocument mUIAmalgumResultsDocument;
        
        private UIAmalgumResultsDocument1 mUIAmalgumResultsDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumAmalgumDocument : HtmlDocument
    {
        
        public UIAmalgumAmalgumDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Amalgum";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/";
            this.WindowTitles.Add("Amalgum - Amalgum");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRegisterHyperlink
        {
            get
            {
                if ((this.mUIRegisterHyperlink == null))
                {
                    this.mUIRegisterHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "registerLink";
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"registerLink\" href=\"/Account/Registe";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIRegisterHyperlink.WindowTitles.Add("Amalgum - Amalgum");
                    #endregion
                }
                return this.mUIRegisterHyperlink;
            }
        }
        
        public HtmlDiv UIAmalgumAnOpenAccePane
        {
            get
            {
                if ((this.mUIAmalgumAnOpenAccePane == null))
                {
                    this.mUIAmalgumAnOpenAccePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAmalgumAnOpenAccePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAmalgumAnOpenAccePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAmalgumAnOpenAccePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Amalgum\r\n\r\n\r\n\r\n\r\n   \r\n\r\n\r\n\r\nAn Open Acce";
                    this.mUIAmalgumAnOpenAccePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAmalgumAnOpenAccePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "container body-content";
                    this.mUIAmalgumAnOpenAccePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"container body-content\"";
                    this.mUIAmalgumAnOpenAccePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUIAmalgumAnOpenAccePane.WindowTitles.Add("Amalgum - Amalgum");
                    #endregion
                }
                return this.mUIAmalgumAnOpenAccePane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRegisterHyperlink;
        
        private HtmlDiv mUIAmalgumAnOpenAccePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumRegisterDocument : HtmlDocument
    {
        
        public UIAmalgumRegisterDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Register";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Account/Register";
            this.WindowTitles.Add("Amalgum - Register");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "FORM";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "form-horizontal";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"form-horizontal\" role=\"form\" acti";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlEdit UIEmailAddressEdit
        {
            get
            {
                if ((this.mUIEmailAddressEdit == null))
                {
                    this.mUIEmailAddressEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "EmailAddress";
                    this.mUIEmailAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "EmailAddress";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "EmailAddress";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"EmailAddress\" class=\"form-control\"";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIEmailAddressEdit.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUIEmailAddressEdit;
            }
        }
        
        public HtmlEdit UISubmitEdit
        {
            get
            {
                if ((this.mUISubmitEdit == null))
                {
                    this.mUISubmitEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISubmitEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "submit";
                    this.mUISubmitEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUISubmitEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISubmitEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISubmitEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISubmitEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "btn btn-default";
                    this.mUISubmitEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"submit\" valu";
                    this.mUISubmitEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUISubmitEdit.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUISubmitEdit;
            }
        }
        
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UIConfirmpasswordEdit
        {
            get
            {
                if ((this.mUIConfirmpasswordEdit == null))
                {
                    this.mUIConfirmpasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Confirm password";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ConfirmPassword\" class=\"form-contr";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIConfirmpasswordEdit.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUIConfirmpasswordEdit;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUILoginHyperlink.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlEdit mUIEmailAddressEdit;
        
        private HtmlEdit mUISubmitEdit;
        
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUIConfirmpasswordEdit;
        
        private HtmlHyperlink mUILoginHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UINotificationToolBar : WinToolBar
    {
        
        public UINotificationToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Notification";
            this.WindowTitles.Add("Amalgum - Register");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Amalgum - Register");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumLoginDocument : HtmlDocument
    {
        
        public UIAmalgumLoginDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Log in";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Account/Login";
            this.WindowTitles.Add("Amalgum - Log in");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "login";
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"login\" value";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUILoginEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumAmalgumDocument1 : HtmlDocument
    {
        
        public UIAmalgumAmalgumDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Amalgum";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search/Index";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Search/Index";
            this.WindowTitles.Add("Amalgum - Amalgum");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISearchStringEdit
        {
            get
            {
                if ((this.mUISearchStringEdit == null))
                {
                    this.mUISearchStringEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchStringEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "searchString";
                    this.mUISearchStringEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "searchString";
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"searchString\" class=\"form-control\"";
                    this.mUISearchStringEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISearchStringEdit.WindowTitles.Add("Amalgum - Amalgum");
                    #endregion
                }
                return this.mUISearchStringEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISearchStringEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumResultsDocument : HtmlDocument
    {
        
        public UIAmalgumResultsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Results";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search/Results";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Search/Results?searchString=radiation";
            this.WindowTitles.Add("Amalgum - Results");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem1stNanoIBCTConfeHyperlink
        {
            get
            {
                if ((this.mUIItem1stNanoIBCTConfeHyperlink == null))
                {
                    this.mUIItem1stNanoIBCTConfeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem1stNanoIBCTConfeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "displayPdf";
                    this.mUIItem1stNanoIBCTConfeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem1stNanoIBCTConfeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem1stNanoIBCTConfeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " 1st Nano-IBCT Conference 2011 u2013 Radiation Damage of Biomolecular Systems: Na" +
                        "noscale Insights into Ion Beam Cancer Therapy ";
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/1742-6596/373/1/011001/pdf/1742-6596_373_1_011001.pdf";
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://iopscience.iop.org/1742-6596/373/1/011001/pdf/1742-6596_373_1_011001.pdf";
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "articleLink";
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"articleLink\" id=\"displayPdf\" href";
                    this.mUIItem1stNanoIBCTConfeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "9";
                    this.mUIItem1stNanoIBCTConfeHyperlink.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIItem1stNanoIBCTConfeHyperlink;
            }
        }
        
        public HtmlHyperlink UIFavoritesHyperlink
        {
            get
            {
                if ((this.mUIFavoritesHyperlink == null))
                {
                    this.mUIFavoritesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Favorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Search/UserFavorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Search/UserFavorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Search/UserFavorites\"";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIFavoritesHyperlink.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIFavoritesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem1stNanoIBCTConfeHyperlink;
        
        private HtmlHyperlink mUIFavoritesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumResultsDocument1 : HtmlDocument
    {
        
        public UIAmalgumResultsDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Results";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search/UserFavorites";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Search/UserFavorites";
            this.WindowTitles.Add("Amalgum - Results");
            #endregion
        }
        
        #region Properties
        public UIAmalgumPane UIAmalgumPane
        {
            get
            {
                if ((this.mUIAmalgumPane == null))
                {
                    this.mUIAmalgumPane = new UIAmalgumPane(this);
                }
                return this.mUIAmalgumPane;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUILoginHyperlink.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public HtmlHyperlink UILogoutHyperlink
        {
            get
            {
                if ((this.mUILogoutHyperlink == null))
                {
                    this.mUILogoutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Account/Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Account/Logout\"";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUILogoutHyperlink.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUILogoutHyperlink;
            }
        }
        
        public HtmlDiv UIResultsarticlesfoundPane
        {
            get
            {
                if ((this.mUIResultsarticlesfoundPane == null))
                {
                    this.mUIResultsarticlesfoundPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIResultsarticlesfoundPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIResultsarticlesfoundPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIResultsarticlesfoundPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Results\r\n\r\narticles found ";
                    this.mUIResultsarticlesfoundPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIResultsarticlesfoundPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIResultsarticlesfoundPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIResultsarticlesfoundPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUIResultsarticlesfoundPane.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIResultsarticlesfoundPane;
            }
        }
        
        public HtmlHyperlink UIFavoritesHyperlink
        {
            get
            {
                if ((this.mUIFavoritesHyperlink == null))
                {
                    this.mUIFavoritesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIFavoritesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Favorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Search/UserFavorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Search/UserFavorites";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Search/UserFavorites\"";
                    this.mUIFavoritesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIFavoritesHyperlink.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIFavoritesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIAmalgumPane mUIAmalgumPane;
        
        private HtmlHyperlink mUILoginHyperlink;
        
        private HtmlHyperlink mUILogoutHyperlink;
        
        private HtmlDiv mUIResultsarticlesfoundPane;
        
        private HtmlHyperlink mUIFavoritesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumPane : HtmlDiv
    {
        
        public UIAmalgumPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "accordion";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Amalgum\r\n\r\n\r\n\r\n\r\n   ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"accordion\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "6";
            this.WindowTitles.Add("Amalgum - Results");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAmalgumPane1
        {
            get
            {
                if ((this.mUIAmalgumPane1 == null))
                {
                    this.mUIAmalgumPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAmalgumPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAmalgumPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAmalgumPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Amalgum\r\n\r\n\r\n\r\n\r\n   ";
                    this.mUIAmalgumPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAmalgumPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIAmalgumPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIAmalgumPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
                    this.mUIAmalgumPane1.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIAmalgumPane1;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row show";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row show\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
                    this.mUIItemPane.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlDiv UIItemPane1
        {
            get
            {
                if ((this.mUIItemPane1 == null))
                {
                    this.mUIItemPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "input-group";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"input-group\"";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "10";
                    this.mUIItemPane1.WindowTitles.Add("Amalgum - Results");
                    #endregion
                }
                return this.mUIItemPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAmalgumPane1;
        
        private HtmlDiv mUIItemPane;
        
        private HtmlDiv mUIItemPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAccessibilitySetupAsWindow : WinWindow
    {
        
        public UIAccessibilitySetupAsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Accessibility Setup Assistant";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Accessibility Setup Assistant");
            #endregion
        }
        
        #region Properties
        public UIAccessibilitySetupAsTitleBar UIAccessibilitySetupAsTitleBar
        {
            get
            {
                if ((this.mUIAccessibilitySetupAsTitleBar == null))
                {
                    this.mUIAccessibilitySetupAsTitleBar = new UIAccessibilitySetupAsTitleBar(this);
                }
                return this.mUIAccessibilitySetupAsTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAccessibilitySetupAsTitleBar mUIAccessibilitySetupAsTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAccessibilitySetupAsTitleBar : WinTitleBar
    {
        
        public UIAccessibilitySetupAsTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Accessibility Setup Assistant");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Accessibility Setup Assistant");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIReadingUntaggedDocumWindow : WinWindow
    {
        
        public UIReadingUntaggedDocumWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Reading Untagged Document";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Reading Untagged Document");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "GroupBox";
            this.WindowTitles.Add("Reading Untagged Document");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Reading Untagged Document");
            #endregion
        }
        
        #region Properties
        public WinButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[WinButton.PropertyNames.Name] = "Cancel";
                    this.mUICancelButton.WindowTitles.Add("Reading Untagged Document");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICancelButton;
        #endregion
    }
}
