//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Article> T_Article { get; set; }
        public virtual DbSet<T_ArticleAuthor> T_ArticleAuthor { get; set; }
        public virtual DbSet<T_ArticleFullMeDa> T_ArticleFullMeDa { get; set; }
        public virtual DbSet<T_ArticleSmallMeDa> T_ArticleSmallMeDa { get; set; }
        public virtual DbSet<T_ArticleSmallMeDa_02> T_ArticleSmallMeDa_02 { get; set; }
        public virtual DbSet<T_ArticleVeryFullMeDa> T_ArticleVeryFullMeDa { get; set; }
        public virtual DbSet<T_ArticleVeryFullMeDa_02> T_ArticleVeryFullMeDa_02 { get; set; }
        public virtual DbSet<T_Author> T_Author { get; set; }
        public virtual DbSet<T_AuthorSmallestMeDa> T_AuthorSmallestMeDa { get; set; }
        public virtual DbSet<T_AuthorSmallMeDa> T_AuthorSmallMeDa { get; set; }
        public virtual DbSet<T_AuthorSmallMeDa_02> T_AuthorSmallMeDa_02 { get; set; }
        public virtual DbSet<T_IOP_4162014_DATA> T_IOP_4162014_DATA { get; set; }
        public virtual DbSet<T_IOP_4162014_DATA_02> T_IOP_4162014_DATA_02 { get; set; }
        public virtual DbSet<T_PublisherSmallMeDa> T_PublisherSmallMeDa { get; set; }
        public virtual DbSet<T_SubjectSmallMeDa> T_SubjectSmallMeDa { get; set; }
        public virtual DbSet<T_SubjectSmallMeDa_02> T_SubjectSmallMeDa_02 { get; set; }
        public virtual DbSet<T_ArticleExtraId> T_ArticleExtraId { get; set; }
        public virtual DbSet<T_ArticleSSN> T_ArticleSSN { get; set; }
        public virtual DbSet<T_Language> T_Language { get; set; }
        public virtual DbSet<T_MiddleMan02> T_MiddleMan02 { get; set; }
        public virtual DbSet<T_Publisher> T_Publisher { get; set; }
        public virtual DbSet<T_Subject> T_Subject { get; set; }
        public virtual DbSet<T_Type> T_Type { get; set; }
    }
}
