//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ArticleVeryFullMeDa
    {
        public int ID { get; set; }
        public string aSSN { get; set; }
        public string bSSN { get; set; }
        public string Creator { get; set; }
        public string ExtraId1 { get; set; }
        public string ExtraId2 { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public string PubLanguage { get; set; }
        public string Relation { get; set; }
        public string Subject { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
