//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MiddleMan02
    {
        public string n { get; set; }
        public System.DateTime i { get; set; }
        public string c { get; set; }
    }
}
