//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserArticle
    {
        public int UserId { get; set; }
        public int ArticleId { get; set; }
    
        public virtual User User { get; set; }
    }
}
