// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Explore page
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIAmalgumAmalgumGoogleWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uIItemDocument = this.UIAmalgumAmalgumGoogleWindow.UIAmalgumRegisterGooglClient.UIItemDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIAmalgumAmalgumGoogleWindow.UIAmalgumRegisterGooglClient.UIChromeLegacyWindowDocument;
            WinClient uIItemClient = this.UIItemWindow.UIItemWindow1.UIItemWindow.UIItemClient;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(1286, 26));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(594, 196));

            // Type 'shaymas123{Tab}123456' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys, ModifierKeys.None);

            // Last mouse action was not recorded.

            // Type '12' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(535, 278));

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(524, 240));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -205, 12);

            // Type '123456' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys2, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(433, 277));

            // Type '123456' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys3, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(443, 329));

            // Type 'thisemail@this.com' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys4, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(384, 407));

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(576, 332));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -235, -42);

            // Type '{Back}' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys5, ModifierKeys.None);

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(478, 289));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -79, -18);

            // Type '{Back}{Back}' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys6, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(399, 215));

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(518, 181));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -181, 1);

            // Type '{Back}' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys7, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(354, 408));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1330, 28));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(542, 199));

            // Type 'shay' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys8, ModifierKeys.None);

            // Click client
            Mouse.Click(uIItemClient, new Point(166, 6));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(510, 246));

            // Type '123456' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys9, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(472, 345));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(509, 134));

            // Type 'ra' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethod1Params.UIItemDocumentSendKeys10, ModifierKeys.None);

            // Click client
            Mouse.Click(uIItemClient, new Point(268, 12));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1351, 137));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1321, 264));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1324, 306));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1322, 345));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(434, 22));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(373, 37));
        }
        
        /// <summary>
        /// Login
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinClient uIShaymasIrvingGoogleGClient1 = this.UIShaymasIrvingGoogleGWindow.UIShaymasIrvingGoogleGClient.UIShaymasIrvingGoogleGClient1;
            WinListItem uIGoogleChromeListItem = this.UIProgramManagerWindow.UIDesktopList.UIGoogleChromeListItem;
            WinEdit uIAddressandsearchbarEdit = this.UIAmalgumAmalgumGoogleWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit;
            WinClient uIChromeLegacyWindowClient = this.UIAmalgumAmalgumGoogleWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowClient;
            WinClient uIChromeLegacyWindowClient1 = this.UIAmalgumAmalgumGoogleWindow.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowClient;
            #endregion

            // Click 'Shaymas Irving - Google+ - Google Chrome' client
            Mouse.Click(uIShaymasIrvingGoogleGClient1, new Point(1501, 19));

            // Double-Click 'Google Chrome' list item
            Mouse.DoubleClick(uIGoogleChromeListItem, new Point(65, 44));

            // Type '********' in 'Address and search bar' text box
            uIAddressandsearchbarEdit.Password = this.RecordedMethod2Params.UIAddressandsearchbarEditPassword;

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(232, 234));

            // Type '********' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.RecordedMethod2Params.UIAddressandsearchbarEditSendKeys, true);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient1, new Point(170, 402));
        }
        
        /// <summary>
        /// Login2
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            HtmlEdit uIUsernameEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UILoginEdit;
            #endregion

            // Go to web page 'http://localhost:50380/Account/Login' using new browser instance
            this.UIAOLcomNewsSportsWeatWindow.LaunchUrl(new System.Uri(this.RecordedMethod3Params.UIAOLcomNewsSportsWeatWindowUrl));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod3Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod3Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod3Params.UIPasswordEditPassword;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(122, 16));
        }
        
        /// <summary>
        /// login3
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            WinEdit uIAddressEdit = this.UIAOLcomNewsSportsWeatWindow.UIItemWindow.UIAddressBarClient.UIAddressEdit;
            WinEdit uIAddressandsearchusinEdit = this.UIAOLcomNewsSportsWeatWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            HtmlHyperlink uILoginHyperlink = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumAmalgumDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UILoginEdit;
            #endregion

            // Click 'Address' text box
            Mouse.Click(uIAddressEdit, new Point(268, 12));

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(268, 6));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(20, 23));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod4Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod4Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod4Params.UIPasswordEditPassword;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(108, 18));
        }
        
        /// <summary>
        /// RecordedMethod5 - Use 'RecordedMethod5Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            WinTitleBar uIAOLcomNewsSportsWeatTitleBar = this.UIAOLcomNewsSportsWeatWindow.UIAOLcomNewsSportsWeatTitleBar;
            HtmlDiv uIAolheaderPane = this.UIAOLcomNewsSportsWeatWindow.UIAOLcomNewsSportsWeatDocument.UIAolheaderPane;
            BrowserWindow uIAOLcomNewsSportsWeatWindow = this.UIAOLcomNewsSportsWeatWindow;
            HtmlHyperlink uILoginHyperlink = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumAmalgumDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UILoginEdit;
            #endregion

            // Go to web page 'http://hp-laptop.aol.com/' using new browser instance
            this.UIAOLcomNewsSportsWeatWindow.LaunchUrl(new System.Uri(this.RecordedMethod5Params.UIAOLcomNewsSportsWeatWindowUrl));

            // Last mouse action was not recorded.

            // Click 'AOL.com - News, Sports, Weather, Entertainment, St...' title bar
            Mouse.Click(uIAOLcomNewsSportsWeatTitleBar, new Point(492, 6));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'aol-header' pane at (1, 1)
            Mouse.Hover(uIAolheaderPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://localhost:50380/'
            uIAOLcomNewsSportsWeatWindow.NavigateToUrl(new System.Uri(this.RecordedMethod5Params.UIAOLcomNewsSportsWeatWindowUrl1));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(30, 23));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod5Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod5Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod5Params.UIPasswordEditPassword;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(92, 6));
        }
        
        /// <summary>
        /// Login3
        /// </summary>
        public void RecordedMethod6()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumAmalgumDocument.UILoginHyperlink;
            HtmlEdit uIUsernameEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UIPasswordEdit;
            HtmlEdit uILoginEdit = this.UIAOLcomNewsSportsWeatWindow.UIAmalgumLoginDocument.UILoginEdit;
            #endregion

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(39, 25));

            // Type 'shaymas123' in 'User name' text box
            uIUsernameEdit.Text = this.RecordedMethod6Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.RecordedMethod6Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod6Params.UIPasswordEditPassword;

            // Click 'login' text box
            Mouse.Click(uILoginEdit, new Point(107, 18));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }
        
        public virtual RecordedMethod5Params RecordedMethod5Params
        {
            get
            {
                if ((this.mRecordedMethod5Params == null))
                {
                    this.mRecordedMethod5Params = new RecordedMethod5Params();
                }
                return this.mRecordedMethod5Params;
            }
        }
        
        public virtual RecordedMethod6Params RecordedMethod6Params
        {
            get
            {
                if ((this.mRecordedMethod6Params == null))
                {
                    this.mRecordedMethod6Params = new RecordedMethod6Params();
                }
                return this.mRecordedMethod6Params;
            }
        }
        
        public UIAmalgumAmalgumGoogleWindow UIAmalgumAmalgumGoogleWindow
        {
            get
            {
                if ((this.mUIAmalgumAmalgumGoogleWindow == null))
                {
                    this.mUIAmalgumAmalgumGoogleWindow = new UIAmalgumAmalgumGoogleWindow();
                }
                return this.mUIAmalgumAmalgumGoogleWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIShaymasIrvingGoogleGWindow UIShaymasIrvingGoogleGWindow
        {
            get
            {
                if ((this.mUIShaymasIrvingGoogleGWindow == null))
                {
                    this.mUIShaymasIrvingGoogleGWindow = new UIShaymasIrvingGoogleGWindow();
                }
                return this.mUIShaymasIrvingGoogleGWindow;
            }
        }
        
        public UIProgramManagerWindow UIProgramManagerWindow
        {
            get
            {
                if ((this.mUIProgramManagerWindow == null))
                {
                    this.mUIProgramManagerWindow = new UIProgramManagerWindow();
                }
                return this.mUIProgramManagerWindow;
            }
        }
        
        public UIAOLcomNewsSportsWeatWindow UIAOLcomNewsSportsWeatWindow
        {
            get
            {
                if ((this.mUIAOLcomNewsSportsWeatWindow == null))
                {
                    this.mUIAOLcomNewsSportsWeatWindow = new UIAOLcomNewsSportsWeatWindow();
                }
                return this.mUIAOLcomNewsSportsWeatWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private RecordedMethod4Params mRecordedMethod4Params;
        
        private RecordedMethod5Params mRecordedMethod5Params;
        
        private RecordedMethod6Params mRecordedMethod6Params;
        
        private UIAmalgumAmalgumGoogleWindow mUIAmalgumAmalgumGoogleWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIShaymasIrvingGoogleGWindow mUIShaymasIrvingGoogleGWindow;
        
        private UIProgramManagerWindow mUIProgramManagerWindow;
        
        private UIAOLcomNewsSportsWeatWindow mUIAOLcomNewsSportsWeatWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'shaymas123{Tab}123456' in document
        /// </summary>
        public string UIItemDocumentSendKeys = "shaymas123{Tab}123456";
        
        /// <summary>
        /// Type '12' in document
        /// </summary>
        public string UIItemDocumentSendKeys1 = "12";
        
        /// <summary>
        /// Type '123456' in document
        /// </summary>
        public string UIItemDocumentSendKeys2 = "123456";
        
        /// <summary>
        /// Type '123456' in document
        /// </summary>
        public string UIItemDocumentSendKeys3 = "123456";
        
        /// <summary>
        /// Type 'thisemail@this.com' in document
        /// </summary>
        public string UIItemDocumentSendKeys4 = "thisemail@this.com";
        
        /// <summary>
        /// Type '{Back}' in document
        /// </summary>
        public string UIItemDocumentSendKeys5 = "{Back}";
        
        /// <summary>
        /// Type '{Back}{Back}' in document
        /// </summary>
        public string UIItemDocumentSendKeys6 = "{Back}{Back}";
        
        /// <summary>
        /// Type '{Back}' in document
        /// </summary>
        public string UIItemDocumentSendKeys7 = "{Back}";
        
        /// <summary>
        /// Type 'shay' in document
        /// </summary>
        public string UIItemDocumentSendKeys8 = "shay";
        
        /// <summary>
        /// Type '123456' in document
        /// </summary>
        public string UIItemDocumentSendKeys9 = "123456";
        
        /// <summary>
        /// Type 'ra' in document
        /// </summary>
        public string UIItemDocumentSendKeys10 = "ra";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type '********' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditPassword = "WpYLUN/3BV6PJdsexinoykVTGn/DoeAH/g+Bi97awn1oBD9cKV6IcB6CJRSxkdLb";
        
        /// <summary>
        /// Type '********' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "8/khZ2upZSC4xdUX4D+GXZYS94GKJRpLpie2kEV6APabpENdnzhJPw==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:50380/Account/Login' using new browser instance
        /// </summary>
        public string UIAOLcomNewsSportsWeatWindowUrl = "http://localhost:50380/Account/Login";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod4Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod5'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod5Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://hp-laptop.aol.com/' using new browser instance
        /// </summary>
        public string UIAOLcomNewsSportsWeatWindowUrl = "http://hp-laptop.aol.com/";
        
        /// <summary>
        /// Go to web page 'http://localhost:50380/'
        /// </summary>
        public string UIAOLcomNewsSportsWeatWindowUrl1 = "http://localhost:50380/";
        
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod6'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod6Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'shaymas123' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "shaymas123";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumAmalgumGoogleWindow : WinWindow
    {
        
        public UIAmalgumAmalgumGoogleWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Amalgum - Amalgum - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
            this.WindowTitles.Add("Amalgum - Register - Google Chrome");
            this.WindowTitles.Add("Amalgum - Log in - Google Chrome");
            this.WindowTitles.Add("Amalgum - Results - Google Chrome");
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIAmalgumRegisterGooglClient UIAmalgumRegisterGooglClient
        {
            get
            {
                if ((this.mUIAmalgumRegisterGooglClient == null))
                {
                    this.mUIAmalgumRegisterGooglClient = new UIAmalgumRegisterGooglClient(this);
                }
                return this.mUIAmalgumRegisterGooglClient;
            }
        }
        
        public UIAddressandsearchbarGroup UIAddressandsearchbarGroup
        {
            get
            {
                if ((this.mUIAddressandsearchbarGroup == null))
                {
                    this.mUIAddressandsearchbarGroup = new UIAddressandsearchbarGroup(this);
                }
                return this.mUIAddressandsearchbarGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIAmalgumRegisterGooglClient mUIAmalgumRegisterGooglClient;
        
        private UIAddressandsearchbarGroup mUIAddressandsearchbarGroup;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "165795712";
            this.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
            this.WindowTitles.Add("Amalgum - Register - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Amalgum - Register - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumRegisterGooglClient : WinClient
    {
        
        public UIAmalgumRegisterGooglClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Amalgum - Register - Google Chrome");
            this.WindowTitles.Add("Amalgum - Log in - Google Chrome");
            this.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
            this.WindowTitles.Add("Amalgum - Results - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIItemDocument.WindowTitles.Add("Amalgum - Register - Google Chrome");
                    this.mUIItemDocument.WindowTitles.Add("Amalgum - Log in - Google Chrome");
                    this.mUIItemDocument.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
                    #endregion
                }
                return this.mUIItemDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Amalgum - Register - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Amalgum - Log in - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Amalgum - Amalgum - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Amalgum - Results - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddressandsearchbarGroup : WinGroup
    {
        
        public UIAddressandsearchbarGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address and search bar";
            this.WindowTitles.Add("New Tab - Google Chrome");
            this.WindowTitles.Add("Amalgum - Log in - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("New Tab - Google Chrome");
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("Amalgum - Log in - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "197264512";
            this.WindowTitles.Add("Amalgum - Log in - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Amalgum - Log in - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "197264512";
            this.WindowTitles.Add("Amalgum - Log in - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Amalgum - Log in - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
            #endregion
        }
        
        #region Properties
        public WinClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new WinClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIShaymasIrvingGoogleGWindow : WinWindow
    {
        
        public UIShaymasIrvingGoogleGWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Shaymas Irving - Google+ - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Shaymas Irving - Google+ - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIShaymasIrvingGoogleGClient UIShaymasIrvingGoogleGClient
        {
            get
            {
                if ((this.mUIShaymasIrvingGoogleGClient == null))
                {
                    this.mUIShaymasIrvingGoogleGClient = new UIShaymasIrvingGoogleGClient(this);
                }
                return this.mUIShaymasIrvingGoogleGClient;
            }
        }
        #endregion
        
        #region Fields
        private UIShaymasIrvingGoogleGClient mUIShaymasIrvingGoogleGClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIShaymasIrvingGoogleGClient : WinClient
    {
        
        public UIShaymasIrvingGoogleGClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Shaymas Irving - Google+ - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIShaymasIrvingGoogleGClient1
        {
            get
            {
                if ((this.mUIShaymasIrvingGoogleGClient1 == null))
                {
                    this.mUIShaymasIrvingGoogleGClient1 = new WinClient(this);
                    #region Search Criteria
                    this.mUIShaymasIrvingGoogleGClient1.SearchProperties[WinControl.PropertyNames.Instance] = "2";
                    this.mUIShaymasIrvingGoogleGClient1.WindowTitles.Add("Shaymas Irving - Google+ - Google Chrome");
                    #endregion
                }
                return this.mUIShaymasIrvingGoogleGClient1;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIShaymasIrvingGoogleGClient1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProgramManagerWindow : WinWindow
    {
        
        public UIProgramManagerWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Program Manager";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Progman";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public UIDesktopList UIDesktopList
        {
            get
            {
                if ((this.mUIDesktopList == null))
                {
                    this.mUIDesktopList = new UIDesktopList(this);
                }
                return this.mUIDesktopList;
            }
        }
        #endregion
        
        #region Fields
        private UIDesktopList mUIDesktopList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDesktopList : WinList
    {
        
        public UIDesktopList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinList.PropertyNames.Name] = "Desktop";
            this.WindowTitles.Add("Program Manager");
            #endregion
        }
        
        #region Properties
        public WinListItem UIGoogleChromeListItem
        {
            get
            {
                if ((this.mUIGoogleChromeListItem == null))
                {
                    this.mUIGoogleChromeListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIGoogleChromeListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Google Chrome";
                    this.mUIGoogleChromeListItem.WindowTitles.Add("Program Manager");
                    #endregion
                }
                return this.mUIGoogleChromeListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIGoogleChromeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAOLcomNewsSportsWeatWindow : BrowserWindow
    {
        
        public UIAOLcomNewsSportsWeatWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "AOL.com - News, Sports, Weather, Entertainment, Stocks & Local";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("AOL.com - News, Sports, Weather, Entertainment, Stocks & Local");
            this.WindowTitles.Add("Amalgum - Log in");
            this.WindowTitles.Add("http://localhost:50380/");
            this.WindowTitles.Add("Amalgum - Amalgum");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAmalgumLoginDocument UIAmalgumLoginDocument
        {
            get
            {
                if ((this.mUIAmalgumLoginDocument == null))
                {
                    this.mUIAmalgumLoginDocument = new UIAmalgumLoginDocument(this);
                }
                return this.mUIAmalgumLoginDocument;
            }
        }
        
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIAddressBarClient1 UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient1(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIAmalgumAmalgumDocument UIAmalgumAmalgumDocument
        {
            get
            {
                if ((this.mUIAmalgumAmalgumDocument == null))
                {
                    this.mUIAmalgumAmalgumDocument = new UIAmalgumAmalgumDocument(this);
                }
                return this.mUIAmalgumAmalgumDocument;
            }
        }
        
        public WinTitleBar UIAOLcomNewsSportsWeatTitleBar
        {
            get
            {
                if ((this.mUIAOLcomNewsSportsWeatTitleBar == null))
                {
                    this.mUIAOLcomNewsSportsWeatTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIAOLcomNewsSportsWeatTitleBar.WindowTitles.Add("AOL.com - News, Sports, Weather, Entertainment, Stocks & Local");
                    this.mUIAOLcomNewsSportsWeatTitleBar.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUIAOLcomNewsSportsWeatTitleBar;
            }
        }
        
        public UIAOLcomNewsSportsWeatDocument UIAOLcomNewsSportsWeatDocument
        {
            get
            {
                if ((this.mUIAOLcomNewsSportsWeatDocument == null))
                {
                    this.mUIAOLcomNewsSportsWeatDocument = new UIAOLcomNewsSportsWeatDocument(this);
                }
                return this.mUIAOLcomNewsSportsWeatDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAmalgumLoginDocument mUIAmalgumLoginDocument;
        
        private UIItemWindow3 mUIItemWindow;
        
        private UIAddressBarClient1 mUIAddressBarClient;
        
        private UIAmalgumAmalgumDocument mUIAmalgumAmalgumDocument;
        
        private WinTitleBar mUIAOLcomNewsSportsWeatTitleBar;
        
        private UIAOLcomNewsSportsWeatDocument mUIAOLcomNewsSportsWeatDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumLoginDocument : HtmlDocument
    {
        
        public UIAmalgumLoginDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Log in";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/Account/Login";
            this.WindowTitles.Add("Amalgum - Log in");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "UserName";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "UserName";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User name";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"UserName\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "login";
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"login\" value";
                    this.mUILoginEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUILoginEdit.WindowTitles.Add("Amalgum - Log in");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "AddressDisplay Control";
            this.WindowTitles.Add("http://localhost:50380/");
            #endregion
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("http://localhost:50380/");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address";
                    this.mUIAddressEdit.WindowTitles.Add("http://localhost:50380/");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAddressBarClient1 : WinClient
    {
        
        public UIAddressBarClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("Amalgum - Amalgum");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Amalgum - Amalgum");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAmalgumAmalgumDocument : HtmlDocument
    {
        
        public UIAmalgumAmalgumDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Amalgum - Amalgum";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:50380/";
            this.WindowTitles.Add("Amalgum - Amalgum");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:50380/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUILoginHyperlink.WindowTitles.Add("Amalgum - Amalgum");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILoginHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAOLcomNewsSportsWeatDocument : HtmlDocument
    {
        
        public UIAOLcomNewsSportsWeatDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AOL.com - News, Sports, Weather, Entertainment, Stocks & Local";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://hp-laptop.aol.com/";
            this.WindowTitles.Add("AOL.com - News, Sports, Weather, Entertainment, Stocks & Local");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAolheaderPane
        {
            get
            {
                if ((this.mUIAolheaderPane == null))
                {
                    this.mUIAolheaderPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAolheaderPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "aol-header";
                    this.mUIAolheaderPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAolheaderPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "AOL.com - News, Sports, Weather, Enterta";
                    this.mUIAolheaderPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAolheaderPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "aol-global-header light";
                    this.mUIAolheaderPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"aol-global-header light\" id=\"aol-header\"";
                    this.mUIAolheaderPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
                    this.mUIAolheaderPane.WindowTitles.Add("AOL.com - News, Sports, Weather, Entertainment, Stocks & Local");
                    #endregion
                }
                return this.mUIAolheaderPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAolheaderPane;
        #endregion
    }
}
